extends: airbnb
parser: babel-eslint
env:
  es6: true
  browser: true
  node: true
  mocha: true
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - app
pseserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    jsx: true
rules:
  arrow-body-style: 0
  max-len: 0
  import/no-unresolved: 0
  no-console: 0
  no-use-before-define: 0
  no-underscore-dangle: 0
  no-class-assign: 0
  no-extra-boolean-cast: 0
  no-nested-ternary: 0
  consistent-return: 0
  eol-last: 0
  jsx-quotes:
    - 2
    - prefer-single
  react/jsx-sort-props: 0
  react/jsx-space-before-closing: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx", ".es6"] }]
  react/prefer-stateless-function: 0
  react/jsx-no-bind: 0
  react/jsx-first-prop-new-line: 0
  react/react-in-jsx-scope: 0
  react/no-multi-comp: 0
  react/no-string-refs: 0
  react/prop-types: 0
  react/self-closing-comp: 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
